import os
from pathlib import Path
from dotenv import load_dotenv

_RUTA_ENV = Path(__file__).resolve().parents[1] / ".env"
load_dotenv(_RUTA_ENV)

KNOX_URL_BASE = os.environ["KNOX_BASE_URL"]
KNOX_TIEMPO_ESPERA_SEGUNDOS = int(os.environ["KNOX_TIMEOUT_SECONDS"])
KNOX_CLIENT_IDENTIFIER_CO = os.environ["KNOX_CLIENT_IDENTIFIER_CO"]
KNOX_RUTA_LLAVES_CO = os.environ["KNOX_RUTA_LLAVES_CO"]
KNOX_AUDIENCIA = os.environ["KNOX_AUDIENCIA"]
KNOX_ALGORITMO = os.environ["KNOX_ALGORITMO"]
KNOX_EXPIRACION_SEG = int(os.environ["KNOX_EXPIRACION_SEG"])
KNOX_VALIDEZ_MINUTOS = int(os.environ["KNOX_VALIDEZ_MINUTOS"])

ALO_API_CLAVE = os.environ["ALO_API_KEY"]

TRUSTONIC_URL_BASE = os.environ["TRUSTONIC_BASE_URL"]
TRUSTONIC_API_CLAVE = os.environ["TRUSTONIC_API_KEY"]
TRUSTONIC_TIEMPO_ESPERA_SEGUNDOS = int(os.environ["TRUSTONIC_TIMEOUT_SECONDS"])
TRUSTONIC_ENCABEZADO_AUTORIZACION = os.environ["TRUSTONIC_AUTH_HEADER"]
TRUSTONIC_PREFIJO_AUTORIZACION = os.environ["TRUSTONIC_AUTH_PREFIX"]

NUOVO_URL_BASE = os.environ["NUOVO_BASE_URL"]
NUOVO_API_CLAVE = os.environ["NUOVO_API_KEY"]
NUOVO_TIEMPO_ESPERA_SEGUNDOS = int(os.environ["NUOVO_TIMEOUT_SECONDS"])

MOTOSAFE_URL_BASE = os.environ["MOTOSAFE_BASE_URL"]
MOTOSAFE_API_CLAVE = os.environ["MOTOSAFE_API_KEY"]
MOTOSAFE_TIEMPO_ESPERA_SEGUNDOS = int(os.environ["MOTOSAFE_TIMEOUT_SECONDS"])
